/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ActRouteImport } from './routes/act'
import { Route as EventsRouteImport } from './routes/events'
import { Route as FightRouteImport } from './routes/fight'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as GrassrootsRouteImport } from './routes/grassroots'
import { Route as LearnRouteImport } from './routes/learn'
import { Route as MapRouteImport } from './routes/map'
import { Route as PackRouteImport } from './routes/pack'
import { Route as PromiseRouteImport } from './routes/promise'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ActRoute = ActRouteImport.update({
  id: '/act',
  path: '/act',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const FightRoute = FightRouteImport.update({
  id: '/fight',
  path: '/fight',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const GrassrootsRoute = GrassrootsRouteImport.update({
  id: '/grassroots',
  path: '/grassroots',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnRoute = LearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const PackRoute = PackRouteImport.update({
  id: '/pack',
  path: '/pack',
  getParentRoute: () => rootRouteImport,
} as any)
const PromiseRoute = PromiseRouteImport.update({
  id: '/promise',
  path: '/promise',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/act': typeof ActRoute
  '/events': typeof EventsRoute
  '/fight': typeof FightRoute
  '/gallery': typeof GalleryRoute
  '/grassroots': typeof GrassrootsRoute
  '/learn': typeof LearnRoute
  '/map': typeof MapRoute
  '/pack': typeof PackRoute
  '/promise': typeof PromiseRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/act': typeof ActRoute
  '/events': typeof EventsRoute
  '/fight': typeof FightRoute
  '/gallery': typeof GalleryRoute
  '/grassroots': typeof GrassrootsRoute
  '/learn': typeof LearnRoute
  '/map': typeof MapRoute
  '/pack': typeof PackRoute
  '/promise': typeof PromiseRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/act': typeof ActRoute
  '/events': typeof EventsRoute
  '/fight': typeof FightRoute
  '/gallery': typeof GalleryRoute
  '/grassroots': typeof GrassrootsRoute
  '/learn': typeof LearnRoute
  '/map': typeof MapRoute
  '/pack': typeof PackRoute
  '/promise': typeof PromiseRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/act'
    | '/events'
    | '/fight'
    | '/gallery'
    | '/grassroots'
    | '/learn'
    | '/map'
    | '/pack'
    | '/promise'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/act'
    | '/events'
    | '/fight'
    | '/gallery'
    | '/grassroots'
    | '/learn'
    | '/map'
    | '/pack'
    | '/promise'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/act'
    | '/events'
    | '/fight'
    | '/gallery'
    | '/grassroots'
    | '/learn'
    | '/map'
    | '/pack'
    | '/promise'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ActRoute: typeof ActRoute
  EventsRoute: typeof EventsRoute
  FightRoute: typeof FightRoute
  GalleryRoute: typeof GalleryRoute
  GrassrootsRoute: typeof GrassrootsRoute
  LearnRoute: typeof LearnRoute
  MapRoute: typeof MapRoute
  PackRoute: typeof PackRoute
  PromiseRoute: typeof PromiseRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/act': {
      id: '/act'
      path: '/act'
      fullPath: '/act'
      preLoaderRoute: typeof ActRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fight': {
      id: '/fight'
      path: '/fight'
      fullPath: '/fight'
      preLoaderRoute: typeof FightRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grassroots': {
      id: '/grassroots'
      path: '/grassroots'
      fullPath: '/grassroots'
      preLoaderRoute: typeof GrassrootsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn': {
      id: '/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof LearnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pack': {
      id: '/pack'
      path: '/pack'
      fullPath: '/pack'
      preLoaderRoute: typeof PackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/promise': {
      id: '/promise'
      path: '/promise'
      fullPath: '/promise'
      preLoaderRoute: typeof PromiseRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ActRoute: ActRoute,
  EventsRoute: EventsRoute,
  FightRoute: FightRoute,
  GalleryRoute: GalleryRoute,
  GrassrootsRoute: GrassrootsRoute,
  LearnRoute: LearnRoute,
  MapRoute: MapRoute,
  PackRoute: PackRoute,
  PromiseRoute: PromiseRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
